config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :forum_threads do
    resources :forum_posts, module: :forum_threads
  end

  root to: 'forum_threads#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/forum_post.rb
# == Schema Information
#
# Table name: forum_posts
#
#  id              :integer          not null, primary key
#  forum_thread_id :integer
#  user_id         :integer
#  body            :text
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class ForumPost < ApplicationRecord

  belongs_to :forum_thread
  belongs_to :user, optional: true
end

app/models/forum_thread.rb
# == Schema Information
#
# Table name: forum_threads
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  subject    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class ForumThread < ApplicationRecord
  
  belongs_to :user
  has_many :forum_posts

  accepts_nested_attributes_for :forum_posts

  validates :subject, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  has_many :forum_threads
  has_many :forum_posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/forum_threads_controller.rb
class ForumThreadsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_forum_thread, except: [:index, :new, :create]


  def index
    @forum_threads = ForumThread.all
  end

  def show
    @forum_post = ForumPost.new
  end

  def new
    @forum_thread = ForumThread.new
    @forum_thread.forum_posts.build
  end

  def create
    @forum_thread = current_user.forum_threads.new(forum_thread_params)
    @forum_thread.forum_posts.first.user_id = current_user.id

    if @forum_thread.save!
      redirect_to @forum_thread
    else
      render :new
    end
  end


  private

    def set_forum_thread
      @forum_thread = ForumThread.find(params[:id])
    end

    def forum_thread_params
      params.require(:forum_thread).permit(:subject, forum_posts_attributes: [:body])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_url(email, size)
    gravatar_id = Digest::MD5::hexdigest(email).downcase
    default_url = "#{asset_url 'avatars/avatar.png'}"
    url = "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}&d=#{CGI::escape(default_url)}"
  end
end

app/views/forum_threads/_form.html.erb
<%= form_for @forum_thread do |f| %>
  <div class="form-group">
    <%= f.text_field :subject, placeholder: 'Subject', class: 'form-control' %>
  </div>

  <%= f.fields_for :forum_posts do |p| %>
    <div class="form-group">
      <%= p.text_area :body, placeholder: 'Add a comment...', rows: 10, class: 'form-control' %>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.submit 'Create Post', class: 'btn btn-outline-primary' %>
  </div>
<% end %>

app/views/forum_threads/index.html.erb
<h1>Hello</h1>

app/views/forum_threads/new.html.erb
<%= render 'shared/logged_in_user' %>

<div class="card user_content">
  <h1 class="display-4">New Thread</h1>
  <p class="lead">
    Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Duis mollis, est non commodo luctus.
  </p>

  <%= render 'form' %>

</div>

app/views/forum_threads/show.html.erb
<%= render 'shared/logged_in_user' %>

<div class="card user_content">
  <h1 class="display-4"><%= @forum_thread.subject %></h1>
  <small class="text-muted">Posted by: <%= @forum_thread.user.email %></small>
  <hr>
  <p class="lead">
    <%= @forum_post.body %>
  </p>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>rForum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <nav class="navbar navbar-toggleable-md fixed-top navbar-light bg-faded">
    <div class="container">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="#">rForum</a>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>                        
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to 'New Thread', new_forum_thread_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to 'Logout', destroy_user_session_path, class: 'nav-link', method: :delete %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to 'Login', new_user_session_path, class: 'nav-link' %>
              </li>
            <% end %>
          </ul>
          <form class="form-inline mt-2 mt-md-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>

    <div class="container">
      <%= yield %>
    </div>
</html>

app/views/shared/_logged_in_user.html.erb
<div class="user_bar">
      <div class="card">
        <div class="card-img-top" style="background-image: url('<%= asset_path "images/backgrounds/iceland.jpg" %>'); height: 150px; background-size: cover;"></div>
        <div class="card-block text-center">
          <a href="profile/index.html">
            <%= image_tag gravatar_url("#{current_user.email}", 80), alt: 'Profile Avatar', class: 'rounded-circle avatar' %>
          </a>

          <h6 class="card-title">
            <a class="bhm" href="profile/index.html"><%= current_user.email %></a>
          </h6>

          <p class="zw">I wish i was a little bit taller, wish i was a baller, wish i had a girl…&nbsp;also.</p>

          <ul class="biu">
            <li class="biv">
              <a href="#userModal" class="bhm" data-toggle="modal">
                Friends
                <h6 class="yx">12M</h6>
              </a>
            </li>

            <li class="biv">
              <a href="#userModal" class="bhm" data-toggle="modal">
                Enemies
                <h6 class="yx">1</h6>
              </a>
            </li>
          </ul>
        </div>
      </div>

      <div class="card">
        <div class="card-block">
          <h6 class="card-title">About <small>· <a href="#">Edit</a></small></h6>
          <ul class="de aqs">
            <li><span class="apv h atz zo"></span>Went to <a href="#">Oh, Canada</a>
            </li><li><span class="apv h bgo zo"></span>Became friends with <a href="#">Obama</a>
            </li><li><span class="apv h aym zo"></span>Worked at <a href="#">Github</a>
            </li><li><span class="apv h azc zo"></span>Lives in <a href="#">San Francisco, CA</a>
            </li><li><span class="apv h bal zo"></span>From <a href="#">Seattle, WA</a>
          </li></ul>
        </div>
      </div>
      
    </div>